# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:25


from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [("migrations", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('idconcert', models.IntegerFieldField()),
            ],
        ),
    ]